---
build_from:
  aarch64: ghcr.io/priyankub/python-matter-server:stable
  amd64: ghcr.io/priyankub/python-matter-server:stable
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.5.0
