---
version: 1.0.4
slug: matter_server_test
name: Matter Server Test
description: Matter WebSocket Server for Home Assistant Matter support.
url: >-
  https://github.com/priyankub/hassio-addons/tree/main/matter_server
arch:
  - aarch64
discovery:
  - matter
hassio_api: true
homeassistant: 2023.12.0
# IPC is only used within the Add-on
host_ipc: false
host_network: true
host_dbus: true
init: false
options:
  log_level: info
  beta: false
schema:
  log_level: list(debug|info|warning|error|critical)
  beta: bool?
ports:
  5580/tcp: null
stage: stable
startup: services
